min_yield_pct: 8.0
user_agent: "Mozilla/5.0 (compatible; MursBotLite/1.0; +compliance; personal use)"
throttle_seconds: 1.2
timeout_seconds: 25

price_min_eur: 1000000   # 1 M€
price_max_eur: 3000000   # 3 M€

cities:
  - Paris
  - Lyon
  - Marseille
  - Bordeaux
  - Toulouse
  - Lille
  - Nice
  - Nantes
  - Montpellier
  - Rennes
  - Strasbourg
  - Grenoble
  - Dijon
  - Angers
  - Reims
  - Tours
  - Clermont-Ferrand
  - Saint-Étienne
  - Nîmes
  - Avignon
  - Béziers
  - Perpignan
  - Toulon
  - Le Havre
  - Rouen
  - Orléans
  - Metz
  - Nancy
  - Caen
  - Poitiers
  - Limoges
  - Annecy
  - Aix-en-Provence
  - Bayonne
  - Pau
  - La Rochelle
  - Valence
  - Chambéry
  - Mulhouse
  - Brest
  - Quimper
  - Vannes
  - Amiens
  - Chartres

queries:
  - "murs occupés"
  - "locataire en place"
  - "investisseur rendement"
  - "murs commerciaux"
  - "emplacement n°1"
  - "loyers garantis"
  - "bail 3/6/9"

sources:
  - name: CessionPME
    domain: cessionpme.com
    search_urls:
      - "https://www.cessionpme.com/annonces,vente-murs-commerciaux,0,0,offre,fr,1,1,0,0,0,0,0,0,0,0,0,0,{city},0,0,0,0"
      - "https://www.cessionpme.com/annonces,vente-murs-commerciaux,0,0,offre,fr,1,1,0,0,0,0,0,0,0,0,0,0,{query},0,0,0,0"
  - name: BureauxLocaux
    domain: bureauxlocaux.com
    search_urls:
      - "https://www.bureauxlocaux.com/immobilier-entreprise/vente/local-commercial/{city}"
  - name: MursCommerciaux
    domain: murscommerciaux.com
    search_urls:
      - "https://www.murscommerciaux.com/recherche?recherche={query}"
      - "https://www.murscommerciaux.com/recherche?recherche={city}"
  - name: SeLogerPro
    domain: seloger.com
    search_urls:
      - "https://www.seloger.com/list.htm?types=2&projects=2&enterprise=1&PLACE={city}"
  - name: LeBonCoin
    domain: leboncoin.fr
    search_urls:
      - "https://www.leboncoin.fr/recherche?category=9&text={query}%20{city}"
