name: Crawl Murs Commerciaux (Lite)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * *"   # tous les jours 06:00 UTC

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show runner info
        run: |
          python3 --version || true
          uname -a || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (robuste)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          python - << 'PY'
          import sys, pkgutil
          print("PYTHON:", sys.version)
          print("PACKAGES:", sorted([m.name for m in pkgutil.iter_modules() if m.name in ("requests","bs4","pandas","yaml","PyYAML")]))
          PY

      - name: Run crawler (verbose)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -e
          python main.py

      - name: Upload artifacts (CSVs) même si erreur
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            output/*.csv
            output/**/*.csv
          if-no-files-found: warn
